DATABASE_USER = "MannerDatebase"
DATABASE_PASSWORD = "1145141919810"
DATABASE_HOST = "192.168.79.128"
DATABASE_PORT = "3306"
DATABASE_NAME = "mannerdatebase"





SQLALCHEMY_DATABASE_URL = f"mysql+pymysql://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}"