name: Release

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get package version
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create Release Tag
        if: matrix.os == 'ubuntu-latest'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag -a v${{ steps.package_version.outputs.version }} -m "Release v${{ steps.package_version.outputs.version }}"
          git push origin v${{ steps.package_version.outputs.version }}

      - name: Install dependencies
        run: npm install

      - name: Build Vue app
        run: npm run build

      - name: Zip Vue dist (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cd dist
          7z a dist.zip ./*
          cd ..

      - name: Zip Vue dist (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          cd dist
          zip -r dist.zip ./*
          cd ..

      - name: Build Electron app
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          name: Release v${{ steps.package_version.outputs.version }}
          files: |
            buileder/*
            dist/dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
